version: '3.8'

services:
  # PostgreSQL for local development
  postgres:
    image: postgres:15-alpine
    container_name: quotes_postgres_dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-quotes_db}
      - POSTGRES_USER=${POSTGRES_USER:-quotes_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-quotes_password}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./infrastructure/postgres/import-prod-data.sql:/docker-entrypoint-initdb.d/02-import.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-quotes_user} -d ${POSTGRES_DB:-quotes_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_dev_data:

networks:
  default:
    name: quotes_dev_network