# Generated by Django 5.0.4 on 2024-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='book',
            field=models.CharField(blank=True, max_length=200, verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='main.type'),
        ),
    ]
