# Generated by Django 5.2.5 on 2025-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_quote_author_alter_quote_book_alter_quote_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200, verbose_name="Topic")),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="topics",
            field=models.ManyToManyField(blank=True, to="main.topic"),
        ),
    ]
