# Generated by Django 5.2.5 on 2025-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_topic_quote_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="type",
            field=models.ManyToManyField(blank=True, to="main.type"),
        ),
    ]
